/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as AuthedInstallningarRouteImport } from './routes/_authed/installningar'
import { Route as AuthedProfilIndexRouteImport } from './routes/_authed/profil/index'
import { Route as AuthedProfilUsernameRouteImport } from './routes/_authed/profil/$username'
import { Route as AuthedProfilRedigeraRouteImport } from './routes/_authed/profil/redigera'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInstallningarRoute = AuthedInstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfilIndexRoute = AuthedProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfilUsernameRoute = AuthedProfilUsernameRouteImport.update({
  id: '/profil/$username',
  path: '/profil/$username',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfilRedigeraRoute = AuthedProfilRedigeraRouteImport.update({
  id: '/profil/redigera',
  path: '/profil/redigera',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/villkor': typeof VillkorRoute
  '/installningar': typeof AuthedInstallningarRoute
  '/profil/$username': typeof AuthedProfilUsernameRoute
  '/profil/redigera': typeof AuthedProfilRedigeraRoute
  '/profil/': typeof AuthedProfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/villkor': typeof VillkorRoute
  '/installningar': typeof AuthedInstallningarRoute
  '/profil/$username': typeof AuthedProfilUsernameRoute
  '/profil/redigera': typeof AuthedProfilRedigeraRoute
  '/profil': typeof AuthedProfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/villkor': typeof VillkorRoute
  '/_authed/installningar': typeof AuthedInstallningarRoute
  '/_authed/profil/$username': typeof AuthedProfilUsernameRoute
  '/_authed/profil/redigera': typeof AuthedProfilRedigeraRoute
  '/_authed/profil/': typeof AuthedProfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integritetspolicy'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/villkor'
    | '/installningar'
    | '/profil/$username'
    | '/profil/redigera'
    | '/profil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integritetspolicy'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/villkor'
    | '/installningar'
    | '/profil/$username'
    | '/profil/redigera'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/integritetspolicy'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/villkor'
    | '/_authed/installningar'
    | '/_authed/profil/$username'
    | '/_authed/profil/redigera'
    | '/_authed/profil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VillkorRoute: typeof VillkorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/installningar': {
      id: '/_authed/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AuthedInstallningarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profil/': {
      id: '/_authed/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof AuthedProfilIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profil/$username': {
      id: '/_authed/profil/$username'
      path: '/profil/$username'
      fullPath: '/profil/$username'
      preLoaderRoute: typeof AuthedProfilUsernameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profil/redigera': {
      id: '/_authed/profil/redigera'
      path: '/profil/redigera'
      fullPath: '/profil/redigera'
      preLoaderRoute: typeof AuthedProfilRedigeraRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedInstallningarRoute: typeof AuthedInstallningarRoute
  AuthedProfilUsernameRoute: typeof AuthedProfilUsernameRoute
  AuthedProfilRedigeraRoute: typeof AuthedProfilRedigeraRoute
  AuthedProfilIndexRoute: typeof AuthedProfilIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedInstallningarRoute: AuthedInstallningarRoute,
  AuthedProfilUsernameRoute: AuthedProfilUsernameRoute,
  AuthedProfilRedigeraRoute: AuthedProfilRedigeraRoute,
  AuthedProfilIndexRoute: AuthedProfilIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VillkorRoute: VillkorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
